### ISSUE TITLE
kergen-map returning error

### ISSUE THREAD

**Issue by demonacle** [nichoski/kergen#1]
Hi,

First, thanks for the script. It's similar to an idea I've been toying with for a while.

On running kergen -g I get the following error:

/usr/bin/python3.3: can't open file 'kergen-map.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.3/kergen", line 50, in <module>
    kernel_options = subprocess.check_output(['python', 'kergen-map.py'], universal_newlines=True)[:-1].split(' ')
  File "/usr/lib64/python3.3/subprocess.py", line 589, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['python', 'kergen-map.py']' returned non-zero exit status 2

.config still seems to be created successfully, and I'm running build now.

Thanks,
Neil.

**Comment by nichoski** [comment]
I'm sorry. I just fixed the bug. kergen was trying to call kergen-map.py, when it should have called kergen-map.
Try it out now.
Thanks.

**Comment by demonacle** [comment]
That's done it. Thanks.
