### ISSUE TITLE
kergen-0.1.1, kergen-map throws traceback when there is no /dev/sdX device

### ISSUE THREAD

**Issue by marcin-github** [nichoski/kergen#2]
Hi!
I tried to use kergen-map on vps (KVM), path to block device is /dev/vdX . kergen-map throws:
<code># kergen-map 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.3/kergen-map", line 158, in <module>
    file_system_kernel_options = generate_file_system_kernel_options()
  File "/usr/lib/python-exec/python3.3/kergen-map", line 147, in generate_file_system_kernel_options
    fs_info = subprocess.check_output('mount | grep \/dev\/sd', shell=True, universal_newlines=True)[:-1]
  File "/usr/lib64/python3.3/subprocess.py", line 589, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'mount | grep \/dev\/sd' returned non-zero exit status 1</code>

**Comment by marcin-github** [comment]
kergen-mod also doesn't work on host with /dev/sda. It looks that greping from output of mount isn't the best way to find out block device.
<code>
# mount  | grep sd

# 

# lsblk -d
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda    8:0    0 149,1G  0 disk 
sdb    8:16   0 149,1G  0 disk 
sdc    8:32   0 149,1G  0 disk 
sdd    8:48   0 465,8G  0 disk 
sde    8:64   0 149,1G  0 disk

# grep sd /proc/mounts

# 

</code>

I've got root filesystem mounted by initrd and it is on lvm (and lvm is on the raid).

**Comment by nichoski** [comment]
The block devices are found in /sys/block/.
The grepping of mount is to find out filesystems of mounted partitions. 
I don't have experience with raid/lvm, would 'parted' show the right info? If not, do you have any idea how I could get the filesystems info that would work universally?
Thanks.

**Comment by marcin-github** [comment]
If you only want to know which filesystem is used you can find it in /proc/mount, e.g.:
<code>
# grep " / " /proc/mounts

/dev/mapper/system10-slash / ext4 rw,noatime,stripe=256,data=ordered 0 0
</code> So you can search for single slash in second column.
But on very old redhat you get:
<code>
$ grep " / " /proc/mounts 

rootfs / rootfs rw 0 0
/dev/root / ext3 rw,data=ordered 0 0
</code> You'll get two lines, and you can ignore "rootfs" filesystem.
I can't say how it looks on other distros and other configuration of root filesystem.

**Comment by nichoski** [comment]
I rewrote the generating of file systems using different approach. It first loads all possible file systems from the kernel sources, and then it searches for each of them in /proc/mounts. Works well on my system. Would you mind testing on yours?
Thanks.

**Comment by marcin-github** [comment]
Now works without problem. But I found another issue:
<code>python kergen-map

cat: /sys/bus/usb/devices/_/modalias: No such file or directory
Traceback (most recent call last):
  File "kergen-map", line 171, in <module>
    device_kernel_options = generate_device_kernel_options()
  File "kergen-map", line 105, in generate_device_kernel_options
    sys_usb_info_list = subprocess.check_output('cat /sys/bus/usb/devices/_/modalias', shell=True, universal_newlines=True)
  File "/usr/lib64/python3.3/subprocess.py", line 589, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'cat /sys/bus/usb/devices/*/modalias' returned non-zero exit status 1</code>

Probably you should always check if files exists.

**Comment by nichoski** [comment]
I replaced usage of 'cat' with pure python functions, and I put a check (if file exists) before every file opening.
Let me know if there are any other issues.
Thanks.

**Comment by marcin-github** [comment]
As for know I can't see any new issue. Thank you for fixing earlier problems.
