### ISSUE TITLE
No tarball to downloadd

### ISSUE THREAD

**Issue by marcin-github** [nichoski/kergen#4]
Hi,
could you prepare tarball for version 0.1.3?

**Comment by nichoski** [comment]
Done, it's at
http://whatishacking.org/kergen/downloads/kergen-0.1.3.tar.gz

**Comment by marcin-github** [comment]
Thank you! Would it be big problem to also publish tarball also on github ?

**Comment by nichoski** [comment]
Not a problem, but how?

**Comment by marcin-github** [comment]
I never did it:) I just tried to do it, it looks that you should start on page https://github.com/nichoski/kergen/releases and click on "Draft new release".

**Comment by nichoski** [comment]
Thanks, here it is.
https://github.com/nichoski/kergen/releases/tag/v0.1.3

**Comment by marcin-github** [comment]
Thanks!
Have a nice day.
